### ISSUE TITLE
How do i create 'vcan0' ?

### ISSUE THREAD

**Issue by AnHardt** [philippoo66/vitualE3#1]
How do i create 'vcan0' ?
```
e3@openE3:~/open3e $ python3 virtualE3.py &
[1] 603
e3@openE3:~/open3e $ featuring universal list
ready to go.
Traceback (most recent call last):
  File "/home/e3/open3e/virtualE3.py", line 446, in <module>
    with can.Bus(interface='socketcan', channel=channel, receive_own_messages=False, can_filters=filters) as bus:
  File "/home/e3/.local/lib/python3.9/site-packages/can/util.py", line 378, in wrapper
    return f(*args, **kwargs)
  File "/home/e3/.local/lib/python3.9/site-packages/can/interface.py", line 135, in Bus
    bus = cls(channel, **kwargs)
  File "/home/e3/.local/lib/python3.9/site-packages/can/interfaces/socketcan/socketcan.py", line 706, in __init__
    bind_socket(self.socket, channel)
  File "/home/e3/.local/lib/python3.9/site-packages/can/interfaces/socketcan/socketcan.py", line 512, in bind_socket
    sock.bind((channel,))
OSError: [Errno 19] No such device
SocketcanBus was not properly shut down

```
Please describe in Readme.

**Comment by philippoo66** [comment]
thanks! some lines added to Readme.
greetings!

**Comment by AnHardt** [comment]
Thanks. That helped.
Most of the mentioned commands need a 'sudo' in front. 
It's running now.

**Comment by philippoo66** [comment]
thank you, according hint added.
